import { useState } from 'react'
import { FileArchive } from 'lucide-react'
import { Alert } from '../ui/Alert'
import { Button } from '../ui/Button'
import { Modal } from '../ui/Modal'
import { errorMessage } from '../../services/apiClient'
import { qrService } from '../../services/qrService'
import type { QrSummary } from '../../types/qr'
import { formatNumber } from '../../utils/format'
import { qrExportFilename, renderQrPng, saveBlob } from '../../utils/qr'
import { buildZip } from '../../utils/zip'

function zipName(eventName: string): string {
  const slug = eventName.normalize('NFKD').replace(/[^A-Za-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 40) || 'event'
  const d = new Date()
  const stamp = `${d.getFullYear()}${String(d.getMonth() + 1).padStart(2, '0')}${String(d.getDate()).padStart(2, '0')}-${String(d.getHours()).padStart(2, '0')}${String(d.getMinutes()).padStart(2, '0')}`
  return `QR-Codes-${slug}-${stamp}.zip`
}

/**
 * Export QR Codes (admin): every EXISTING QR of the active event's active
 * attendees as the same PNG as "Download QR", in one ZIP built in the browser.
 * Nothing is generated or changed; attendees without a QR are only counted.
 */
export function ExportQrModal({ summary, onClose }: { summary: QrSummary; onClose: () => void }) {
  const [progress, setProgress] = useState<{ done: number; total: number } | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [result, setResult] = useState<string | null>(null)
  const busy = progress !== null && result === null && error === null

  const run = async () => {
    setError(null)
    setResult(null)
    setProgress({ done: 0, total: summary.generated })
    try {
      const data = await qrService.exportData()
      if (data.items.length === 0) {
        setProgress(null)
        setError('There are no generated QR codes to export.')
        return
      }
      const entries = []
      for (const [index, item] of data.items.entries()) {
        const blob = await renderQrPng(item.qrPayload, item)
        entries.push({ name: qrExportFilename(item.attendeeCode, item.fullName), data: new Uint8Array(await blob.arrayBuffer()) })
        setProgress({ done: index + 1, total: data.items.length })
      }
      saveBlob(buildZip(entries), zipName(data.event.name))
      setResult(`Exported ${formatNumber(entries.length)} QR code${entries.length === 1 ? '' : 's'}.` +
        (data.missing > 0 ? ` ${formatNumber(data.missing)} attendee(s) without a QR were not included.` : ''))
    } catch (caught) {
      setProgress(null)
      setError(errorMessage(caught))
    }
  }

  const nothing = summary.generated === 0

  return (
    <Modal
      open
      title="Export QR codes"
      description="Downloads one ZIP with a PNG for every generated QR code (same image as “Download QR”)."
      onClose={() => !busy && onClose()}
      footer={
        <>
          <Button key="close" variant="secondary" onClick={onClose} disabled={busy}>{result ? 'Close' : 'Cancel'}</Button>
          {!result && (
            <Button key="export" onClick={() => void run()} loading={busy} disabled={nothing || busy} icon={<FileArchive className="size-4" aria-hidden />}>
              {busy ? 'Exporting…' : 'Export ZIP'}
            </Button>
          )}
        </>
      }
    >
      <div className="space-y-4 text-sm" data-testid="qr-export">
        <ul className="space-y-1 rounded-lg bg-slate-50 p-3 text-slate-700" data-testid="qr-export-summary">
          <li><strong className="text-slate-900">{formatNumber(summary.generated)}</strong> QR code{summary.generated === 1 ? '' : 's'} ready</li>
          <li><strong className="text-slate-900">{formatNumber(summary.missing)}</strong> missing QR code{summary.missing === 1 ? '' : 's'}</li>
        </ul>
        {nothing ? (
          <Alert tone="info">No QR codes have been generated yet, so there is nothing to export.</Alert>
        ) : summary.missing > 0 && !result ? (
          <Alert tone="info">
            Attendees without a QR are not included and no QR codes are generated by this export. Use “Generate missing QR codes” first if they should be included.
          </Alert>
        ) : null}
        {!nothing && !result && (
          <p className="text-slate-600">
            Only active attendees are included. Files are named like <span className="font-mono">ATT-0001_Juan_Dela_Cruz.png</span>.
            The ZIP is created on this computer; nothing is stored on the server.
          </p>
        )}
        {busy && progress && (
          <div aria-live="polite">
            <p className="text-slate-700">Creating images… {formatNumber(progress.done)} / {formatNumber(progress.total)}</p>
            <div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-200">
              <div className="h-full bg-brand-600 transition-all" style={{ width: `${progress.total ? Math.round((progress.done / progress.total) * 100) : 0}%` }} />
            </div>
          </div>
        )}
        {error && <Alert tone="error">{error}</Alert>}
        {result && <Alert tone="success">{result}</Alert>}
      </div>
    </Modal>
  )
}
